- name: Install and Run nginx
  hosts: web
  become: yes # its to become a root user
  tasks: #install Nginx
  - name: Insta nginx
    ansible.builtin.package:
      name: nginx
      state: present
  - name: Run Nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
    